### ISSUE TITLE
Kanban board Review request 

### ISSUE THREAD

**Issue by fredo509** [fredo509/Ruby-capstone#34]
Hello👋 ,

We are 3 Members to work on this project @carreraprogrammer , @fpsapc , @fredo509  

For this Milestone we : 

Join a  Team Zoom call.
Create an empty repository for your group project.
Create tasks on our Kanban board based on the [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md).

[Kaban board link](https://github.com/fredo509/Ruby-capstone/projects/1)

**Comment by Ismailco** [comment]
Hi @fredo509, @carreraprogrammer, @fpsapc,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a link to the kanban board

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by brytebee** [comment]
Hi Team👋,

##

### Highlights💡
- A link to the Kanban board is specified.✔️ 
- The team member size is stated.✔️
- The project requirements are covered with the tasks on the Kanban board.✔️
- All tasks have descriptions.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
- This card is unassigned, you must have missed it. You are required to assign every card.

<img width="384" alt="image" src="https://github.com/fredo509/Ruby-capstone/assets/27709832/dac219f7-d51f-4a36-b94e-9607d75be6a8">


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by binhussen** [comment]
Hi @fredo509, @carreraprogrammer and @fpsapc 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Set uped Kanban board ✔️
- Fairway distributed tasks✔️
- Descriptive title with number of points Tasks ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
